---
- name: Packagist Publish
  uses: wscourge/gha-packagist-publish@1.0.2
  with:
    domain: null
    username: ti0rafa
    api_token: fb658f8e9340ceaa12d20d2448de27ebed55e7e9
    package_name: null
    package_base_url: null