on:
  push:
    branches: ['master']

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Update Packagist
        uses: mnavarrocarter/packagist-update@v1.0
        with:
          username: "ti0rafa"
          api_token: ${{ secrets.PACKAGIST_API_TOKEN }}
          package_name: "tiorafa/sparky7"
          domain: "packagist.org"
